### ISSUE TITLE
Liteloader 1.10.2 Menu text broken

### ISSUE THREAD

**Issue by Toadby** [Pokechu22/WorldDownloader#56] opened 2017-04-20 00:58 UTC
![screen shot 2017-04-19 at 5 56 16 pm](https://cloud.githubusercontent.com/assets/16440384/25208429/89ae14ea-2529-11e7-9088-4afee21a2db2.png)
![screen shot 2017-04-19 at 5 56 11 pm](https://cloud.githubusercontent.com/assets/16440384/25208430/89ae85c4-2529-11e7-8f6e-805189c8ea21.png)
The menu text is broken making everything very confusing! Is there an easy fix for this? Should I try using a different mod version? I used 4.0.0.3 for 1.10.2
Thank you

**Comment by Pokechu22** [comment] 2017-04-20 01:11
Duplicate of #31, but I just remembered a change that happened beween 1.10.2 and 1.11: [the lowercasing of files in resource packs](https://minecraft.gamepedia.com/1.11#General_2).  Everything I've been doing is using the lowercase form, and that might be breaking things in 1.10.2 (I don't remember the exact rules 1.10.2 uses for capitalization).  It's probably something like that (separate from the optifine issue), which hopefully should be a trivial fix once I figure out exactly what I'm doing wrong.

I'm not sure why I haven't run into this myself - I'd think that something like this would be common.  Maybe it's also related to windows and case-insensitive paths?  What OS are you running?

**Comment by Toadby** [comment] 2017-04-20 01:58
@Pokechu22 I am on OSX (10.12.3) I do have optifine installed if that affects it?

**Comment by Pokechu22** [comment] 2017-04-20 02:02
It might be either of those.  I don't have access to OSX, so can you check if it still happens with optifine disabled (to see if it's just a property of OSX)?

**Comment by Toadby** [comment] 2017-04-20 02:08
@Pokechu22 Still happens without Optifine :)

**Closed as completed** 2017-04-24 00:59 UTC

**Comment by Pokechu22** [comment] 2017-04-24 01:00
I've pushed a fix that should _hopefully_ solve the problem (now using the correct `en_US` naming instead of `en_us` on 1.10) - it'll be included in the next build.
