### ISSUE TITLE
mod-worlddownloader-baseedit-4.0.5.3-mc1.14.4.zip Sometimes crashes while saving the world.

### ISSUE THREAD

**Issue by MrRibcage** [Pokechu22/WorldDownloader#137] opened 2019-08-09 18:55 UTC
I'm flying through a world I'm wanting to save, and then suddenly, the entire game crashes. Gives me this crash report: 

```
---- Minecraft Crash Report ----
// Why did you do that?

Time: 09/08/19 2:40 PM
Description: WDL mod: exception in onWorldClientTick event

java.lang.NullPointerException: WDL mod: exception in onWorldClientTick event
	at bhr.k(SourceFile:176)
	at bhr.d(SourceFile:808)
	at wdl.WDLEvents.onItemGuiClosed(WDLEvents.java:236)
	at wdl.WDLHooks.onWorldClientTick0(WDLHooks.java:125)
	at wdl.WDLHooks.onWorldClientTick(WDLHooks.java:102)
	at dkf.a(ClientWorld.java:101)
	at cyc.m(SourceFile:1451)
	at cyc.e(SourceFile:925)
	at cyc.b(SourceFile:410)
	at net.minecraft.client.main.Main.main(SourceFile:155)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- World Downloader Mod - Core --
Details:
	WDL version: 4.0.5.3
	Minecraft version: Minecraft 1.14.4 (1.14.4.wdl/WorldDownloader-4.0.5.3/release)
	Expected version: 1.14.4
	Protocol version: 498
	Data version: 1976
	File location: C:\Users\<USERNAME>\AppData\Roaming\.minecraft\versions\1.14.4.wdl\1.14.4.wdl.jar

-- World Downloader Mod - Extensions --
Details:
	Number loaded: 2
	Hologram: Id: Hologram
Version: 2.0
Display name: Hologram support
Main author: Pokechu22
Description: 
Provides basic support for disabling holograms.
Main class: wdl.HologramHandler
Containing file: C:\Users\<USERNAME>\AppData\Roaming\.minecraft\versions\1.14.4.wdl\1.14.4.wdl.jar
Implemented interfaces (2)
0: wdl.api.IEntityManager
1: wdl.api.IWDLModDescripted
Superclass: java.lang.Object
Classloader: sun.misc.Launcher$AppClassLoader@2626b418 (sun.misc.Launcher$AppClassLoader)
Annotations (0)

	EntityRealigner: Id: EntityRealigner
Version: 1.0
Display name: Entity realigner
Main author: Pokechu22
Description: 
Realigns entities to their serverside position to deal with entities that drift clientside (for example, boats).
Main class: wdl.EntityRealigner
Containing file: C:\Users\<USERNAME>\AppData\Roaming\.minecraft\versions\1.14.4.wdl\1.14.4.wdl.jar
Implemented interfaces (2)
0: wdl.api.IEntityEditor
1: wdl.api.IWDLModDescripted
Superclass: java.lang.Object
Classloader: sun.misc.Launcher$AppClassLoader@2626b418 (sun.misc.Launcher$AppClassLoader)
Annotations (0)


-- World Downloader Mod - State --
Details:
	minecraft: cyc@9736d7e
	worldClient: dkf@5c608988
	networkManager: jc@6eb58fdd
	player: dmp['MrRibcage'/1680064, l='MpServer', x=1600.31, y=147.35, z=927.22]
	windowContainer: ayr@4d979f76
	lastClickedBlock: ~~NULL~~
	lastEntity: ~~NULL~~
	saveHandler: coo@559048b3
	chunkLoader: wdl.WDLChunkLoader@471ac7e2
	newTileEntities: {}
	newEntities: {[96, 62]=[arq['Rabbit'/478377, l='MpServer', x=1537.48, y=63.00, z=1003.89]], [96, 64]=[arq['Rabbit'/478759, l='MpServer', x=1551.18, y=63.00, z=1027.20], axw['Boat'/478758, l='MpServer', x=1548.31, y=62.52, z=1034.23]], [96, 63]=[arq['Rabbit'/478378, l='MpServer', x=1551.62, y=64.50, z=1009.35]]}
	entityPositions: {333ce131-3b2b-4efe-ac09-6108b8aad561=[96, 62], 4d484b03-f6e8-4c6c-9b8b-51d89a0537c7=[96, 64], 2afd5317-be18-4487-9a75-a3593ec0dbba=[96, 64], 8e526578-669f-4e28-960f-45e4f25cb416=[96, 63]}
	newMapDatas: {}
	downloading: true
	isMultiworld: true
	propsFound: true
	startOnChange: true
	overrideLastModifiedCheck: false
	saving: false
	worldLoadingDeferred: false
	worldName: Towny
	baseFolderName: Rebel_Federation_Server_Towny
	serverProps: wdl.config.Configuration@1fee3a40
	worldProps: wdl.config.Configuration@6e737ae4
	globalProps: wdl.config.Configuration@39716249
	defaultProps: wdl.config.DefaultConfiguration@28459752
	gameRules: bhn@46179420

-- World Downloader Mod - Server properties --
Details:
	LinkedWorlds: |TownyOrigins|Towny|Towny

-- World Downloader Mod - World properties --
Details:
	WorldName: Towny

-- World Downloader Mod - Global properties --
Details:
	TutorialShown: true
	UpdateETag: "7b8a741c86a7a50209f395ff237d5a88"

-- Sanity checks --
Details:
	TRIPWIRE: Skipped
	VERSION: Passed
	TRANSLATION: Passed
	MIXIN_INVENTORYBASIC: Skipped
	MIXIN_GUIINGAMEMENU: Passed
	MIXIN_WORLDCLIENT: Passed
	MIXIN_NHPC: Passed
	MIXIN_CRASHREPORT: Passed
	ENCODING: Passed

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 901876328 bytes (860 MB) / 1845493760 bytes (1760 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
```

Any idea why? Possible solutions?

**Comment by Pokechu22** [comment] 2019-08-09 19:10
```
java.lang.NullPointerException: WDL mod: exception in onWorldClientTick event
	at bhr.k(SourceFile:176)
	at bhr.d(SourceFile:808)
	at wdl.WDLEvents.onItemGuiClosed(WDLEvents.java:236)
	at wdl.WDLHooks.onWorldClientTick0(WDLHooks.java:125)
	at wdl.WDLHooks.onWorldClientTick(WDLHooks.java:102)
	at dkf.a(ClientWorld.java:101)
	at cyc.m(SourceFile:1451)
	at cyc.e(SourceFile:925)
	at cyc.b(SourceFile:410)
	at net.minecraft.client.main.Main.main(SourceFile:155)
```

is:

```
java.lang.NullPointerException: WDL mod: exception in onWorldClientTick event
	at World.isOutsideBuildHeight(World.java:148)
	at World.getTileEntity(World.java:800)
	at wdl.WDLEvents.onItemGuiClosed(WDLEvents.java:236)
	at wdl.WDLHooks.onWorldClientTick0(WDLHooks.java:125)
	at wdl.WDLHooks.onWorldClientTick(WDLHooks.java:102)
	at ClientWorld.tick(ClientWorld.java:101)
	...
	at net.minecraft.client.main.Main.main(SourceFile:155)
```

`isOutsideBuildHeight` is failing due to a null `BlockPos`.  Looking in the crash report, both `lastClickedBlock` and `lastEntity` are null, so that's at least _why_ it's crashing.  How it got into that state, I'm not sure.

As a check: this happened in the GUI closed event.  Had you opened an inventory of some sort?  Or did it just randomly crash without you opening anything?

**Comment by MrRibcage** [comment] 2019-08-09 20:19
i believe it just randomly crashed. It's possible though that I had my inventory open. Would using the chat bar or changing the item in my hand cause that?

**Comment by MrRibcage** [comment] 2019-08-09 20:33
just happened again, definitely didn't open my inventory, but I did open the pause menu a little before it happened. Could that be the cause? Having the pause menu open for too long?

```
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 09/08/19 4:31 PM
Description: WDL mod: exception in onWorldClientTick event

java.lang.NullPointerException: WDL mod: exception in onWorldClientTick event
	at bhr.k(SourceFile:176)
	at bhr.d(SourceFile:808)
	at wdl.WDLEvents.onItemGuiClosed(WDLEvents.java:236)
	at wdl.WDLHooks.onWorldClientTick0(WDLHooks.java:125)
	at wdl.WDLHooks.onWorldClientTick(WDLHooks.java:102)
	at dkf.a(ClientWorld.java:101)
	at cyc.m(SourceFile:1451)
	at cyc.e(SourceFile:925)
	at cyc.b(SourceFile:410)
	at net.minecraft.client.main.Main.main(SourceFile:155)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- World Downloader Mod - Core --
Details:
	WDL version: 4.0.5.3
	Minecraft version: Minecraft 1.14.4 (1.14.4.wdl/WorldDownloader-4.0.5.3/release)
	Expected version: 1.14.4
	Protocol version: 498
	Data version: 1976
	File location: C:\Users\<USERNAME>\AppData\Roaming\.minecraft\versions\1.14.4.wdl\1.14.4.wdl.jar

-- World Downloader Mod - Extensions --
Details:
	Number loaded: 2
	Hologram: Id: Hologram
Version: 2.0
Display name: Hologram support
Main author: Pokechu22
Description: 
Provides basic support for disabling holograms.
Main class: wdl.HologramHandler
Containing file: C:\Users\<USERNAME>\AppData\Roaming\.minecraft\versions\1.14.4.wdl\1.14.4.wdl.jar
Implemented interfaces (2)
0: wdl.api.IEntityManager
1: wdl.api.IWDLModDescripted
Superclass: java.lang.Object
Classloader: sun.misc.Launcher$AppClassLoader@2626b418 (sun.misc.Launcher$AppClassLoader)
Annotations (0)

	EntityRealigner: Id: EntityRealigner
Version: 1.0
Display name: Entity realigner
Main author: Pokechu22
Description: 
Realigns entities to their serverside position to deal with entities that drift clientside (for example, boats).
Main class: wdl.EntityRealigner
Containing file: C:\Users\<USERNAME>\AppData\Roaming\.minecraft\versions\1.14.4.wdl\1.14.4.wdl.jar
Implemented interfaces (2)
0: wdl.api.IEntityEditor
1: wdl.api.IWDLModDescripted
Superclass: java.lang.Object
Classloader: sun.misc.Launcher$AppClassLoader@2626b418 (sun.misc.Launcher$AppClassLoader)
Annotations (0)


-- World Downloader Mod - State --
Details:
	minecraft: cyc@5e6dcfa
	worldClient: dkf@705b4359
	networkManager: jc@3c79be0f
	player: dmp['MrRibcage'/1880397, l='MpServer', x=1245.70, y=139.43, z=1908.18]
	windowContainer: ayr@734df10b
	lastClickedBlock: ~~NULL~~
	lastEntity: ~~NULL~~
	saveHandler: coo@5ecc8114
	chunkLoader: wdl.WDLChunkLoader@6d7e973b
	newTileEntities: {}
	newEntities: {[81, 113]=[avm['Zombie'/1888908, l='MpServer', x=1310.50, y=30.00, z=1811.50]], [74, 116]=[atx['Lily Pad'/1889283, l='MpServer', x=1193.20, y=62.64, z=1867.99]], [83, 116]=[aue['Creeper'/1888434, l='MpServer', x=1328.13, y=69.00, z=1870.13]], [81, 114]=[avm['Zombie'/1888392, l='MpServer', x=1301.50, y=46.00, z=1833.35]], [79, 113]=[avd['Skeleton'/1888449, l='MpServer', x=1277.50, y=58.00, z=1821.50], aue['Creeper'/1888450, l='MpServer', x=1265.50, y=56.00, z=1812.50], aue['Creeper'/1888451, l='MpServer', x=1265.56, y=56.00, z=1811.21]], [76, 115]=[aug['Drowned'/1889189, l='MpServer', x=1226.11, y=58.00, z=1842.89]], [82, 116]=[aue['Creeper'/1888433, l='MpServer', x=1323.03, y=69.00, z=1869.03]], [78, 112]=[aue['Creeper'/1888516, l='MpServer', x=1263.50, y=56.00, z=1805.50], aue['Creeper'/1888515, l='MpServer', x=1263.50, y=56.00, z=1807.50]], [77, 115]=[axy['Minecart with Chest'/1889125, l='MpServer', x=1247.50, y=15.06, z=1841.50]]}
	entityPositions: {01e50898-7aa0-48a2-a045-a1a1f26689fa=[79, 113], d0787cb0-0ce9-4f3b-99c2-a848afff2de3=[81, 113], 6032f4df-0504-4eee-acef-7797344e74fd=[76, 115], 87f17db7-2395-4138-9d66-d488373a9c2f=[81, 114], 0b29465c-28ee-448d-80ff-b375d4d83f5d=[79, 113], 62020e12-51d3-46f3-97c6-b3f958dd4a8c=[74, 116], da166910-391a-4eb3-9c74-b81ebde07efa=[82, 116], dab3dd79-eec6-4d5f-aa5a-513dbb7ac8e4=[99, 71], c5997901-1c63-4d13-b623-bb9f96465a7e=[78, 112], 7459835d-b0a7-41a7-89c3-e5591f91ecfe=[78, 112], 45e52180-3e49-41b2-9905-ebc41c1c7d31=[99, 71], 431b0b52-2d17-4940-98e4-43af454a7a2d=[83, 116], db9711b8-1c51-46c3-a4d3-2ae6b13a084a=[99, 71], fb8f7c1f-69db-43f9-ba80-393706a13018=[79, 113], 8d89d799-2a23-4b44-8abf-78073347c737=[77, 115]}
	newMapDatas: {}
	downloading: true
	isMultiworld: true
	propsFound: true
	startOnChange: true
	overrideLastModifiedCheck: false
	saving: false
	worldLoadingDeferred: false
	worldName: Towny
	baseFolderName: Rebel_Federation_Server_Towny
	serverProps: wdl.config.Configuration@47955046
	worldProps: wdl.config.Configuration@5bcc2416
	globalProps: wdl.config.Configuration@61b2ca5a
	defaultProps: wdl.config.DefaultConfiguration@78ec5e18
	gameRules: bhn@15962623

-- World Downloader Mod - Server properties --
Details:
	LinkedWorlds: |TownyOrigins|Towny|Towny|Towny

-- World Downloader Mod - World properties --
Details:
	WorldName: Towny

-- World Downloader Mod - Global properties --
Details:
	TutorialShown: true
	UpdateETag: "11cc0b103ba3a3ffea740380e22516e9"

-- Sanity checks --
Details:
	TRIPWIRE: Skipped
	VERSION: Passed
	TRANSLATION: Passed
	MIXIN_INVENTORYBASIC: Skipped
	MIXIN_GUIINGAMEMENU: Passed
	MIXIN_WORLDCLIENT: Passed
	MIXIN_NHPC: Passed
	MIXIN_CRASHREPORT: Passed
	ENCODING: Passed

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 714633088 bytes (681 MB) / 1845493760 bytes (1760 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
```

**Comment by Pokechu22** [comment] 2019-08-10 01:39
I wouldn't expect the pause menu being open too long to cause something like that, nor opening the chat bar nor messing with items.  Of course, that doesn't mean it _wasn't_ the cause, just that I think it's unlikely; there were some changes to inventories that make them a bit closer to other GUIs and maybe opening and closing something would cause it.  However it doesn't seem to be too simple as just opening and closing the pause menu didn't trigger it for me.

One other thing I noticed in that report is `windowContainer: ayr@734df10b`.  `ayr` is `ContainerChest`, though it could be more accurately expressed as just a generic inventory since it's also used by ender chests, barrels, etc.  But more notably, it's also often used by servers for custom menus implemented using inventories.  Does the server you're on use those?

**Comment by MrRibcage** [comment] 2019-08-10 15:04
It does, however I don't believe I used one. It is possible though. The next time I have a chance, I'll start a download, and then open a custom gui, and see if it crashes.

**Comment by MrRibcage** [comment] 2019-08-10 18:15
Okay, so I opened a custom gui, and that definitely crashed it. I don't remember having opened anything right before it crashed for the past few times though. Is it possible that there was delay between opening the gui and the crash?


```
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 10/08/19 2:08 PM
Description: WDL mod: exception in onWorldClientTick event

java.lang.NullPointerException: WDL mod: exception in onWorldClientTick event
	at bhr.k(SourceFile:176)
	at bhr.d(SourceFile:808)
	at wdl.WDLEvents.onItemGuiClosed(WDLEvents.java:236)
	at wdl.WDLHooks.onWorldClientTick0(WDLHooks.java:125)
	at wdl.WDLHooks.onWorldClientTick(WDLHooks.java:102)
	at dkf.a(ClientWorld.java:101)
	at cyc.m(SourceFile:1451)
	at cyc.e(SourceFile:925)
	at cyc.b(SourceFile:410)
	at net.minecraft.client.main.Main.main(SourceFile:155)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- World Downloader Mod - Core --
Details:
	WDL version: 4.0.5.3
	Minecraft version: Minecraft 1.14.4 (1.14.4.wdl/WorldDownloader-4.0.5.3/release)
	Expected version: 1.14.4
	Protocol version: 498
	Data version: 1976
	File location: C:\Users\<USERNAME>\AppData\Roaming\.minecraft\versions\1.14.4.wdl\1.14.4.wdl.jar

-- World Downloader Mod - Extensions --
Details:
	Number loaded: 2
	Hologram: Id: Hologram
Version: 2.0
Display name: Hologram support
Main author: Pokechu22
Description: 
Provides basic support for disabling holograms.
Main class: wdl.HologramHandler
Containing file: C:\Users\<USERNAME>\AppData\Roaming\.minecraft\versions\1.14.4.wdl\1.14.4.wdl.jar
Implemented interfaces (2)
0: wdl.api.IEntityManager
1: wdl.api.IWDLModDescripted
Superclass: java.lang.Object
Classloader: sun.misc.Launcher$AppClassLoader@2626b418 (sun.misc.Launcher$AppClassLoader)
Annotations (0)

	EntityRealigner: Id: EntityRealigner
Version: 1.0
Display name: Entity realigner
Main author: Pokechu22
Description: 
Realigns entities to their serverside position to deal with entities that drift clientside (for example, boats).
Main class: wdl.EntityRealigner
Containing file: C:\Users\<USERNAME>\AppData\Roaming\.minecraft\versions\1.14.4.wdl\1.14.4.wdl.jar
Implemented interfaces (2)
0: wdl.api.IEntityEditor
1: wdl.api.IWDLModDescripted
Superclass: java.lang.Object
Classloader: sun.misc.Launcher$AppClassLoader@2626b418 (sun.misc.Launcher$AppClassLoader)
Annotations (0)


-- World Downloader Mod - State --
Details:
	minecraft: cyc@3938e876
	worldClient: dkf@70b2819f
	networkManager: jc@158e3a79
	player: dmp['MrRibcage'/2101948, l='MpServer', x=1755.50, y=133.48, z=755.60]
	windowContainer: ayr@65dac812
	lastClickedBlock: ~~NULL~~
	lastEntity: ~~NULL~~
	saveHandler: coo@3619ecd
	chunkLoader: wdl.WDLChunkLoader@7de4bd8f
	newTileEntities: {}
	newEntities: {[113, 44]=[arn['Pig'/9, l='MpServer', x=1813.49, y=139.00, z=717.95]], [112, 46]=[arc['Chicken'/10, l='MpServer', x=1793.15, y=137.00, z=749.84]], [111, 45]=[arm['Parrot'/4, l='MpServer', x=1790.40, y=111.00, z=720.85]]}
	entityPositions: {876e42f0-6557-447f-85ac-053154f5a6c6=[113, 44], a7ea6c69-9319-4c61-860a-84eeda654970=[111, 45], 3c11a2ee-8b18-450a-89bd-105e2efbc3d9=[112, 46]}
	newMapDatas: {}
	downloading: true
	isMultiworld: true
	propsFound: true
	startOnChange: true
	overrideLastModifiedCheck: false
	saving: false
	worldLoadingDeferred: false
	worldName: Test
	baseFolderName: Rebel_Federation_Server_Towny
	serverProps: wdl.config.Configuration@193e65d5
	worldProps: wdl.config.Configuration@2a97b4b8
	globalProps: wdl.config.Configuration@250fc0d1
	defaultProps: wdl.config.DefaultConfiguration@7ddf193a
	gameRules: bhn@17a5cb99

-- World Downloader Mod - Server properties --
Details:
	LinkedWorlds: |TownyOrigins|Towny|Towny|Towny|Towny|Test

-- World Downloader Mod - World properties --
Details:
	WorldName: Test

-- World Downloader Mod - Global properties --
Details:
	TutorialShown: true
	UpdateETag: "ce34ec83f4a6b582b06de3a9aa9c1fb3"

-- Sanity checks --
Details:
	TRIPWIRE: Skipped
	VERSION: Passed
	TRANSLATION: Passed
	MIXIN_INVENTORYBASIC: Skipped
	MIXIN_GUIINGAMEMENU: Passed
	MIXIN_WORLDCLIENT: Passed
	MIXIN_NHPC: Passed
	MIXIN_CRASHREPORT: Passed
	ENCODING: Passed

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1067460592 bytes (1018 MB) / 1845493760 bytes (1760 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
```

**Comment by Pokechu22** [comment] 2019-08-10 19:03
I wouldn't expect a significant delay after closing it, but I'm not 100% sure of that.

I _was_ able to reproduce a similar type of crash by right-clicking a chest and then quickly looking upwards at the sky such that I was not looking at any block when the GUI opened.  I know that when looking at another block that isn't a chest, the mod will create a warning but won't crash; I guess something with the way looking works causes both the targeted block and entity to be null if there's nothing in the way.  I should be able to fix that at least, though that doesn't fully explain crashes unrelated to GUIs...

```

---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 8/10/19 11:58 AM
Description: WDL mod: exception in onWorldClientTick event

java.lang.NullPointerException: WDL mod: exception in onWorldClientTick event
	at net.minecraft.world.World.isOutsideBuildHeight(World.java:148)
	at net.minecraft.world.World.getTileEntity(World.java:800)
	at wdl.WDLEvents.onItemGuiClosed(WDLEvents.java:236)
	at wdl.WDLHooks.onWorldClientTick0(WDLHooks.java:125)
	at wdl.WDLHooks.onWorldClientTick(WDLHooks.java:102)
	at net.minecraft.client.world.ClientWorld.tick(ClientWorld.java:101)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1396)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:891)
	at net.minecraft.client.Minecraft.run(Minecraft.java:381)
	at net.minecraft.client.main.Main.main(Main.java:125)
	at mcp.client.Start.main(Start.java:17)

-- World Downloader Mod - State --
Details:
	minecraft: net.minecraft.client.Minecraft@6364d449
	worldClient: net.minecraft.client.world.ClientWorld@fabe3f8
	networkManager: net.minecraft.network.NetworkManager@62099f75
	player: ClientPlayerEntity['Player254'/11, l='MpServer', x=55.80, y=5.63, z=-229.43]
	windowContainer: net.minecraft.inventory.container.ChestContainer@11a88d87
	lastClickedBlock: ~~NULL~~
	lastEntity: ~~NULL~~
	saveHandler: net.minecraft.world.storage.SaveHandler@ce24a98
	chunkLoader: wdl.WDLChunkLoader@496101d1
	newTileEntities: {}
	newEntities: {}
	entityPositions: {}
	newMapDatas: {}
	downloading: true
	isMultiworld: true
	propsFound: true
	startOnChange: true
	overrideLastModifiedCheck: false
	saving: false
	worldLoadingDeferred: false
	worldName: Overworld
	baseFolderName: localhost
	serverProps: wdl.config.Configuration@19858f26
	worldProps: wdl.config.Configuration@4c14ed24
	globalProps: wdl.config.Configuration@523cc8b4
	defaultProps: wdl.config.DefaultConfiguration@139224ab
	gameRules: net.minecraft.world.GameRules@26db7540
```

**Comment by MrRibcage** [comment] 2019-08-10 19:45
Okay, well I think that I must have just miss-remembered, because I can't think of any other reason for a crash like this. I'll mark the issue as closed, since you said you think you can fix it. Good luck, and thanks again for the explanations!

**Comment by Pokechu22** [comment] 2019-08-11 01:27
I prefer keeping issues open until I've actually fixed them (since it helps me keep track, and means that other people can find it more easily).

I do have a tip which might help: when flying around, look towards the ground and try to avoid being too high in the sky.  At least from what I've figured out, you won't have any problems as long as there's a block somewhat in front of you (I think a distance of 20 blocks, but maybe more); if you're flying high up and looking forward then you won't have any blocks but looking down should give something.  That should at least reduce the random crashes.

**Comment by MrRibcage** [comment] 2019-08-11 01:34
Thanks for the tip, will make sure to do this all the time.

**Comment by Pokechu22** [comment] 2019-12-30 04:26
I've released [Version 4.0.6.0](https://github.com/Pokechu22/WorldDownloader/releases/tag/v4.0.6.0) that should fix the crash.

**Comment by MrRibcage** [comment] 2019-12-30 05:28
Cool, thanks for the update!

**Closed as completed** 2020-02-15 20:29 UTC
Labels: bug

**Comment by Pokechu22** [comment] 2020-02-15 20:33
I've fixed handling of fake chests.  Now, if a chest is closed when you weren't looking at a chest when it was opened, it won't be saved and a message explaining that it wasn't saved will be put into chat.  (You should still be able to save these fake chests by looking at a chest block when you open them, though, if that's something you want to do).
