### ISSUE TITLE
Duplicate #31 on 4.0.6.2

### ISSUE THREAD

**Issue by AlphaDelta9** [Pokechu22/WorldDownloader#173] opened 2020-05-23 15:59 UTC
Base Edit 1.12.2, 4.0.5.3 No Issue
Asset Resource Pack temporary resolve the issue

**Comment by Pokechu22** [comment] 2020-05-23 17:50
It works for me with 1.12.2 base edit version 4.0.6.2 installed with MultiMC ([image](https://user-images.githubusercontent.com/8334194/82737018-b0bdeb80-9ce2-11ea-9159-e3c27f58b683.png)).  If you have other mods installed (such as optifine), that could cause it; the base edit does not work well with other mods (use the litemod instead).

#31 / #56 in Minecraft 1.10.2 and earlier was caused by a language file name issue, and 1.12 should not have been affected by the original issue.  So something else is causing it here, I think.

**Comment by AlphaDelta9** [comment] 2020-05-23 18:01
![image](https://user-images.githubusercontent.com/6195505/82737239-2fa63900-9d62-11ea-8663-f1312efce94f.png)
Only with optifine, but remove it still same
I use MultiMC 6.0.11

1.14.4 not affected

**Comment by AlphaDelta9** [comment] 2020-05-23 18:09
LiteLoader version not affected
![image](https://user-images.githubusercontent.com/6195505/82737401-852f1580-9d63-11ea-9dad-d079212800e3.png)

**Comment by AlphaDelta9** [comment] 2020-05-23 18:11
I will try 1.11.2 and version 4.0.6 pre-release for confirmation tomorrow

**Comment by Pokechu22** [comment] 2020-05-23 19:35
For the 1.12.2 base-edit, try re-doing the installation without installing optifine or anything else at all.

**Comment by AlphaDelta9** [comment] 2020-05-24 07:25
New 1.12.2 Instance 
![image](https://user-images.githubusercontent.com/6195505/82748196-b0048280-9dd2-11ea-8596-a05dfeed72b6.png)
Looks strange, 1.11.2 not affected

**Comment by AlphaDelta9** [comment] 2020-05-24 07:28
4.0.6.1
![image](https://user-images.githubusercontent.com/6195505/82748276-26a18000-9dd3-11ea-8cd3-4539fa380dcd.png)
The file differences with 4.0.6.2 only at 3 file refers to WDLHooks (VersionConstants ignored)

**Comment by AlphaDelta9** [comment] 2020-05-24 07:44
I18n.format("gui.advancements") instead I18n.format("gui.advancements", new Object[0])

**Comment by AlphaDelta9** [comment] 2020-05-24 08:40
Followup Pattern:
4.0.6.1 added before Optifine, not loaded
4.0.5.3 & 4.0.6.0 added before Optifine, missing translation

added after Optifine, loaded fine

**Comment by AlphaDelta9** [comment] 2020-05-24 08:44
It seems like the baseedit problem per client basis, thats why you not get the problem. If you think this problem not from the mod, just close it. Thanks for the response

**Comment by Pokechu22** [comment] 2020-05-24 19:04
Can you select "copy debug info" (`wdl.gui.about.debugInfo`) on the about screen on a version where the issue is happening (in singleplayer, the about screen is accessed from `...`; in multiplayer you have to select a second button), and then paste the result here?  It will include information about sanity checks, which will help me decide if this is a problem with the mod or not.

**Comment by AlphaDelta9** [comment] 2020-05-25 09:03
-- World Downloader Mod - Core --
Details:
	WDL version: 4.0.6.2
	Minecraft version: Minecraft 1.12.2 (MultiMC5/WorldDownloader-4.0.6.2/release)
	Expected version: 1.12.2
	Protocol version: 340
	Data version: 1343
	File location: D:\Games\MultiMC\instances\1.14.4\.minecraft\bin\minecraft.jar

-- World Downloader Mod - Extensions --
Details:
	Number loaded: 2
	Hologram: Id: Hologram
Version: 2.0
Display name: Hologram support
Main author: Pokechu22
Description: 
Provides basic support for disabling holograms.
Main class: wdl.HologramHandler
Containing file: D:\Games\MultiMC\instances\1.14.4\.minecraft\bin\minecraft.jar
Implemented interfaces (2)
0: wdl.api.IEntityManager
1: wdl.api.IWDLModDescripted
Superclass: java.lang.Object
Classloader: sun.misc.Launcher$AppClassLoader@7852e922 (sun.misc.Launcher$AppClassLoader)
Annotations (0)

	EntityRealigner: Id: EntityRealigner
Version: 1.0
Display name: Entity realigner
Main author: Pokechu22
Description: 
Realigns entities to their serverside position to deal with entities that drift clientside (for example, boats).
Main class: wdl.EntityRealigner
Containing file: D:\Games\MultiMC\instances\1.14.4\.minecraft\bin\minecraft.jar
Implemented interfaces (2)
0: wdl.api.IEntityEditor
1: wdl.api.IWDLModDescripted
Superclass: java.lang.Object
Classloader: sun.misc.Launcher$AppClassLoader@7852e922 (sun.misc.Launcher$AppClassLoader)
Annotations (0)


-- World Downloader Mod - State --
Details:
	minecraft: bib@475753dd
	worldClient: ~~NULL~~
	networkManager: ~~NULL~~
	player: ~~NULL~~
	windowContainer: ~~NULL~~
	lastClickedBlock: ~~NULL~~
	lastEntity: ~~NULL~~
	saveHandler: ~~NULL~~
	chunkLoader: ~~NULL~~
	newTileEntities: {}
	newEntities: {}
	entityPositions: {}
	newMapDatas: {}
	downloading: false
	isMultiworld: false
	propsFound: false
	startOnChange: false
	overrideLastModifiedCheck: false
	saving: false
	worldLoadingDeferred: false
	worldName: ~~NULL~~
	baseFolderName: ~~NULL~~
	serverProps: wdl.config.Configuration@9203db8
	worldProps: wdl.config.Configuration@9203db8
	globalProps: wdl.config.Configuration@64d0b8e3
	defaultProps: wdl.config.DefaultConfiguration@65d3a83
	gameRules: amr@7be9582e

-- World Downloader Mod - Server properties --
Details:
	-: empty

-- World Downloader Mod - World properties --
Details:
	-: empty

-- World Downloader Mod - Global properties --
Details:
	TutorialShown: true
	UpdateETag: W/"047b93c98d6411a46c247e3519ee92d6"

-- Sanity checks --
Details:
	TRIPWIRE: Passed
	VERSION: Passed
	TRANSLATION: Passed
	MIXIN_INVENTORYBASIC: Passed
	MIXIN_GUIINGAMEMENU: Passed
	MIXIN_WORLDCLIENT: Passed
	MIXIN_NHPC: Passed
	MIXIN_CRASHREPORT: Passed
	ENCODING: Passed

-- World Downloader Mod - Core --
Details:
	WDL version: 4.0.6.2
	Minecraft version: Minecraft 1.12.2 (MultiMC5/WorldDownloader-4.0.6.2/release)
	Expected version: 1.12.2
	Protocol version: 340
	Data version: 1343
	File location: D:\Games\MultiMC\instances\1.14.4\.minecraft\bin\minecraft.jar

-- World Downloader Mod - Extensions --
Details:
	Number loaded: 2
	Hologram: Id: Hologram
Version: 2.0
Display name: Hologram support
Main author: Pokechu22
Description: 
Provides basic support for disabling holograms.
Main class: wdl.HologramHandler
Containing file: D:\Games\MultiMC\instances\1.14.4\.minecraft\bin\minecraft.jar
Implemented interfaces (2)
0: wdl.api.IEntityManager
1: wdl.api.IWDLModDescripted
Superclass: java.lang.Object
Classloader: sun.misc.Launcher$AppClassLoader@7852e922 (sun.misc.Launcher$AppClassLoader)
Annotations (0)

	EntityRealigner: Id: EntityRealigner
Version: 1.0
Display name: Entity realigner
Main author: Pokechu22
Description: 
Realigns entities to their serverside position to deal with entities that drift clientside (for example, boats).
Main class: wdl.EntityRealigner
Containing file: D:\Games\MultiMC\instances\1.14.4\.minecraft\bin\minecraft.jar
Implemented interfaces (2)
0: wdl.api.IEntityEditor
1: wdl.api.IWDLModDescripted
Superclass: java.lang.Object
Classloader: sun.misc.Launcher$AppClassLoader@7852e922 (sun.misc.Launcher$AppClassLoader)
Annotations (0)


-- World Downloader Mod - State --
Details:
	minecraft: bib@475753dd
	worldClient: ~~NULL~~
	networkManager: ~~NULL~~
	player: ~~NULL~~
	windowContainer: ~~NULL~~
	lastClickedBlock: ~~NULL~~
	lastEntity: ~~NULL~~
	saveHandler: ~~NULL~~
	chunkLoader: ~~NULL~~
	newTileEntities: {}
	newEntities: {}
	entityPositions: {}
	newMapDatas: {}
	downloading: false
	isMultiworld: false
	propsFound: false
	startOnChange: false
	overrideLastModifiedCheck: false
	saving: false
	worldLoadingDeferred: false
	worldName: ~~NULL~~
	baseFolderName: ~~NULL~~
	serverProps: wdl.config.Configuration@9203db8
	worldProps: wdl.config.Configuration@9203db8
	globalProps: wdl.config.Configuration@64d0b8e3
	defaultProps: wdl.config.DefaultConfiguration@65d3a83
	gameRules: amr@7be9582e

-- World Downloader Mod - Server properties --
Details:
	-: empty

-- World Downloader Mod - World properties --
Details:
	-: empty

-- World Downloader Mod - Global properties --
Details:
	TutorialShown: true
	UpdateETag: W/"047b93c98d6411a46c247e3519ee92d6"

-- Sanity checks --
Details:
	TRIPWIRE: Passed
	VERSION: Passed
	TRANSLATION: Passed
	MIXIN_INVENTORYBASIC: Passed
	MIXIN_GUIINGAMEMENU: Passed
	MIXIN_WORLDCLIENT: Passed
	MIXIN_NHPC: Passed
	MIXIN_CRASHREPORT: Passed
	ENCODING: Passed

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_252, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), AdoptOpenJDK
	Memory: 396633936 bytes (378 MB) / 853540864 bytes (814 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx2048m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95

**Comment by AlphaDelta9** [comment] 2020-05-25 13:22
-- World Downloader Mod - Core --
Details:
	WDL version: 4.0.6.2
	Minecraft version: Minecraft 1.12.2 (MultiMC5/WorldDownloader-4.0.6.2/release)
	Expected version: 1.12.2
	Protocol version: 340
	Data version: 1343
	File location: D:\Games\MultiMC\instances\1.14.4\.minecraft\bin\minecraft.jar

-- World Downloader Mod - Extensions --
Details:
	Number loaded: 2
	Hologram: Id: Hologram
Version: 2.0
Display name: Hologram support
Main author: Pokechu22
Description: 
Provides basic support for disabling holograms.
Main class: wdl.HologramHandler
Containing file: D:\Games\MultiMC\instances\1.14.4\.minecraft\bin\minecraft.jar
Implemented interfaces (2)
0: wdl.api.IEntityManager
1: wdl.api.IWDLModDescripted
Superclass: java.lang.Object
Classloader: sun.misc.Launcher$AppClassLoader@7852e922 (sun.misc.Launcher$AppClassLoader)
Annotations (0)

	EntityRealigner: Id: EntityRealigner
Version: 1.0
Display name: Entity realigner
Main author: Pokechu22
Description: 
Realigns entities to their serverside position to deal with entities that drift clientside (for example, boats).
Main class: wdl.EntityRealigner
Containing file: D:\Games\MultiMC\instances\1.14.4\.minecraft\bin\minecraft.jar
Implemented interfaces (2)
0: wdl.api.IEntityEditor
1: wdl.api.IWDLModDescripted
Superclass: java.lang.Object
Classloader: sun.misc.Launcher$AppClassLoader@7852e922 (sun.misc.Launcher$AppClassLoader)
Annotations (0)


-- World Downloader Mod - State --
Details:
	minecraft: bib@69339b3b
	worldClient: ~~NULL~~
	networkManager: ~~NULL~~
	player: ~~NULL~~
	windowContainer: ~~NULL~~
	lastClickedBlock: ~~NULL~~
	lastEntity: ~~NULL~~
	saveHandler: ~~NULL~~
	chunkLoader: ~~NULL~~
	newTileEntities: {}
	newEntities: {}
	entityPositions: {}
	newMapDatas: {}
	downloading: false
	isMultiworld: false
	propsFound: false
	startOnChange: false
	overrideLastModifiedCheck: false
	saving: false
	worldLoadingDeferred: false
	worldName: ~~NULL~~
	baseFolderName: ~~NULL~~
	serverProps: wdl.config.Configuration@723c6a25
	worldProps: wdl.config.Configuration@723c6a25
	globalProps: wdl.config.Configuration@232438a8
	defaultProps: wdl.config.DefaultConfiguration@590cdb9a
	gameRules: amr@2c9369c3

-- World Downloader Mod - Server properties --
Details:
	-: empty

-- World Downloader Mod - World properties --
Details:
	-: empty

-- World Downloader Mod - Global properties --
Details:
	TutorialShown: true
	UpdateETag: W/"f7b3d44ea4c652ca8d5c73590d1cd076"

-- Sanity checks --
Details:
	TRIPWIRE: Passed
	VERSION: Passed
	TRANSLATION: ~~ERROR~~ Exception: Translation strings are not present!  All messages will be the untranslated keys (e.g. `wdl.sanity.translation').  Please redownload the mod.  If this problem persists, file a bug report.
	MIXIN_INVENTORYBASIC: Passed
	MIXIN_GUIINGAMEMENU: Passed
	MIXIN_WORLDCLIENT: ~~ERROR~~ Exception: WorldClient is missing base changes!
	MIXIN_NHPC: Passed
	MIXIN_CRASHREPORT: ~~ERROR~~ Exception: CrashReport is missing base changes!
	ENCODING: Passed

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_252, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), AdoptOpenJDK
	Memory: 815922984 bytes (778 MB) / 1032847360 bytes (985 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx2048m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95

**Comment by Pokechu22** [comment] 2020-05-26 23:48
```
-- Sanity checks --
Details:
TRIPWIRE: Passed
VERSION: Passed
TRANSLATION: ~~ERROR~~ Exception: Translation strings are not present! All messages will be the untranslated keys (e.g. `wdl.sanity.translation'). Please redownload the mod. If this problem persists, file a bug report.
MIXIN_INVENTORYBASIC: Passed
MIXIN_GUIINGAMEMENU: Passed
MIXIN_WORLDCLIENT: ~~ERROR~~ Exception: WorldClient is missing base changes!
MIXIN_NHPC: Passed
MIXIN_CRASHREPORT: ~~ERROR~~ Exception: CrashReport is missing base changes!
ENCODING: Passed
```

The failed sanity checks there are caused by a conflict between the base edit and optifine; due to the way the base edit works (directly replacing files), such conflicts aren't possible to fix.  The only way to deal with them is to not use optifine, or to use the litemod version (which uses mixin and is capable of working around such conflicts).  Closing this issue.

**Closed as completed by Pokechu22** 2020-05-26 23:48 UTC
