### ISSUE TITLE
Please make 1.12.2 wdl forge

### ISSUE THREAD

**Issue by CrawLeyYou** [Pokechu22/WorldDownloader#192] opened 2020-09-28 14:21 UTC
Please make 1.12.2 wdl forge

**Comment by RossosHEX** [comment] 2020-09-28 14:38
There's a guide how to install under forge here:
https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2520465-world-downloader-mod-create-backups-of-your-builds#Installation


for more information see issue #184

**Comment by CrawLeyYou** [comment] 2020-09-28 16:00
> There's a guide how to install under forge here:
> https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2520465-world-downloader-mod-create-backups-of-your-builds#Installation
> 
> for more information see issue #184

but not 1.12.2 :/

**Comment by RossosHEX** [comment] 2020-09-28 16:31
Guide: https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1290155-liteloader
&
https://github.com/Pokechu22/WorldDownloader/releases/
"mod-litemodwdl-4.1.0.2-mc1.12.2.litemod"

**Comment by CrawLeyYou** [comment] 2020-09-28 17:17
> Guide: https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1290155-liteloader
> &
> https://github.com/Pokechu22/WorldDownloader/releases/
> "mod-litemodwdl-4.1.0.2-mc1.12.2.litemod"

bro I want forge version :/

**Comment by RossosHEX** [comment] 2020-09-28 17:28
As you wish.

![snap002918e](https://user-images.githubusercontent.com/8318353/94465745-0e9a9c80-01c9-11eb-9f8f-bfa7e3ad32a0.jpg)

**Comment by amoraschi** [comment] 2020-09-28 20:57
Close this please

**Comment by Pokechu22** [comment] 2020-09-28 21:01
Closing as duplicate of #184

**Closed as completed by Pokechu22** 2020-09-28 21:01 UTC
Labels: duplicate
