### ISSUE TITLE
Crash after entering world.

### ISSUE THREAD

**Issue by darkarrow** [Pokechu22/WorldDownloader#11] opened 2015-09-09 15:20 UTC
I'm getting this crash on the latest version of worlddownloader(1.8c-fix1) right after joining a server. This doesn't happen on other servers I've joined while having this mod on but does on this one.

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 9/9/15 11:15 AM
Description: WDL mod: exception in onWorldClientTick event

java.lang.NullPointerException: WDL mod: exception in onWorldClientTick event
	at wdl.WDL.loadWorld(WDL.java:353)
	at wdl.WDLEvents.onWorldLoad(WDLEvents.java:81)
	at wdl.WDLHooks.onWorldClientTick(WDLHooks.java:34)
	at cen.c(WorldClient.java:107)
	at bsu.r(SourceFile:1839)
	at bsu.as(SourceFile:877)
	at bsu.a(SourceFile:314)
	at net.minecraft.client.main.Main.main(SourceFile:120)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 172103712 bytes (164 MB) / 254705664 bytes (242 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0

EDIT: Also I've tried both coremod and liteloader version, they both have the same crash.

**Comment by Pokechu22** [comment] 2015-09-09 19:08
Which server?

----

Notes for myself: From the stacktrace, it looks like the server's brand is `null`.  It shouldn't be `null` in most cases, but if it's not getting sent, that might be why (do some servers not send it?  or is it a race condition?)

**Comment by Pokechu22** [comment] 2015-09-09 19:19
Also, just for clarification, this is a different error than #10 (#10 was caused by the game attempting to remove an entity before the world was fully loaded; this is caused by the check used to determine whether to use spigot entity ranges or vanilla minecraft ones).

**Comment by darkarrow** [comment] 2015-09-09 23:49
the server's dns is mc.worldbuscus.com so far the only one I've found I have the error on. Would this be the reason that connecting with a mini-map also crashes on join?

**Comment by Pokechu22** [comment] 2015-09-10 00:07
Guessing so.  That server probably uses some kind of plugin to hide the server brand (Why?  I have no clue).  

> `Server brand: ~~NULL~~`

That's irritating.  All servers are supposed to have it for debugging reasons.  

In any case, it should be possible to check for null and handle that separately.  (in fact, the current version in development already does).  

In the mean time... I don't want to release a full version just yet, but I can make a quick patch and give you a single file needed.  Give me a few minutes.

**Comment by Pokechu22** [comment] 2015-09-10 02:25
Well, that took a little longer, but I decided to actually do a full release, [1.8c-fix2](https://github.com/Pokechu22/WorldDownloader/releases/tag/1.8c-fix2), that fixes this bug and one where the message options would not get loaded.

**Comment by darkarrow** [comment] 2015-09-10 07:28
Yup, allowed me to join and not crash. Thank you very much!

**Comment by Pokechu22** [comment] 2015-09-10 13:44
OK, closing issue.  Welcome!

**Closed by Pokechu22** 2015-09-10 13:44 UTC
Labels: bug
