### ISSUE TITLE
Crash after joining server 1.13.1 port

### ISSUE THREAD

**Issue by smithonator** [Pokechu22/WorldDownloader#93] opened 2018-09-14 20:34 UTC
Don't know if this a bug or installing error. Followed instructions to install for 1.13.1. Appears to have installed however, when I try and open a 1.13.1 server, it crashes.

<details><summary>Report</summary>

<pre>
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- World Downloader Mod - Core --
Details:
	WDL version: 4.0.3.0
	Minecraft version: Minecraft 1.13-1.13.1 PH (MultiMC5/WorldDownloader-4.0.3.0/release)
	Expected version: 1.13-1.13.1 PH
	Protocol version: 401
	Data version: 1519
	File location: C:\Users\<USERNAME>\Desktop\MultiMC\instances\WDL\.minecraft\bin\minecraft.jar

-- World Downloader Mod - Extensions --
Details:
	Number loaded: 2
	Hologram: Id: Hologram
Version: 2.0
Display name: Hologram support
Main author: Pokechu22
Description: 
Provides basic support for disabling holograms.
Main class: wdl.HologramHandler
Containing file: C:\Users\<USERNAME>\Desktop\MultiMC\instances\WDL\.minecraft\bin\minecraft.jar
Implemented interfaces (2)
0: wdl.api.IEntityManager
1: wdl.api.IWDLModDescripted
Superclass: java.lang.Object
Classloader: sun.misc.Launcher$AppClassLoader@5c647e05 (sun.misc.Launcher$AppClassLoader)
Annotations (0)

	EntityRealigner: Id: EntityRealigner
Version: 1.0
Display name: Entity realigner
Main author: Pokechu22
Description: 
Realigns entities to their serverside position to deal with entities that drift clientside (for example, boats).
Main class: wdl.EntityRealigner
Containing file: C:\Users\<USERNAME>\Desktop\MultiMC\instances\WDL\.minecraft\bin\minecraft.jar
Implemented interfaces (2)
0: wdl.api.IEntityEditor
1: wdl.api.IWDLModDescripted
Superclass: java.lang.Object
Classloader: sun.misc.Launcher$AppClassLoader@5c647e05 (sun.misc.Launcher$AppClassLoader)
Annotations (0)

-- World Downloader Mod - State --
Details:
	minecraft: cfi@4ce2f4d6
	worldClient: ~~NULL~~
	networkManager: ~~NULL~~
	thePlayer: ~~NULL~~
	windowContainer: ~~NULL~~
	lastClickedBlock: ~~NULL~~
	lastEntity: ~~NULL~~
	saveHandler: ~~NULL~~
	chunkLoader: ~~NULL~~
	newTileEntities: {}
	newEntities: {}
	newMapDatas: {}
	downloading: false
	isMultiworld: false
	propsFound: false
	startOnChange: false
	overrideLastModifiedCheck: false
	saving: false
	worldLoadingDeferred: false
	worldName: WorldDownloaderERROR
	baseFolderName: WorldDownloaderERROR
	baseProps: wdl.config.Configuration@58070889
	worldProps: wdl.config.Configuration@5c71329f
	globalProps: wdl.config.Configuration@225fc6a2
	defaultProps: wdl.config.DefaultConfiguration@7940d27b

-- World Downloader Mod - Base properties --
Details:
	-: empty

-- World Downloader Mod - World properties --
Details:
	-: empty

-- World Downloader Mod - Global properties --
Details:
	-: empty

-- System Details --
Details:
	Minecraft Version: 1.13
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_171, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 580492560 bytes (553 MB) / 765460480 bytes (730 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Alex\Desktop\MultiMC\instances\WDL\.minecraft\crash-reports\crash-2018-09-14_19.33.37-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code -1.
</pre>
</details>

**Comment by Pokechu22** [comment] 2018-09-14 20:37
That crash report doesn't seem to be complete (it includes system information, but not the stacktrace itself); can you attach the actual report file in `.minecraft\crash-reports\crash-2018-09-14_19.33.37-client.txt`?

**Comment by smithonator** [comment] 2018-09-18 16:58
Sorry for a delayed reply, been quite busy with work atm.

<details>
<summary>Here's the full report:</summary>

<pre>
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 14/09/18 19:33
Description: WDL mod: exception in onNHPCHandleCustomPayload event

java.lang.NullPointerException: WDL mod: exception in onNHPCHandleCustomPayload event
	at wdl.WDLPluginChannels.getRegisteredChannels(WDLPluginChannels.java:649)
	at wdl.WDLPluginChannels.registerChannels(WDLPluginChannels.java:744)
	at wdl.WDLPluginChannels.onPluginChannelPacket(WDLPluginChannels.java:728)
	at wdl.WDLEvents.onPluginChannelPacket(WDLEvents.java:326)
	at wdl.WDLHooks.onNHPCHandleCustomPayload(WDLHooks.java:330)
	at cqs.a(NetHandlerPlayClient.java:1828)
	at jy.a(SourceFile:57)
	at jy.a(SourceFile:10)
	at ix.a(SourceFile:10)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at k.a(SourceFile:198)
	at cfi.c(SourceFile:808)
	at cfi.a(SourceFile:392)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- World Downloader Mod - Core --
Details:
	WDL version: 4.0.3.0
	Minecraft version: Minecraft 1.13-1.13.1 PH (MultiMC5/WorldDownloader-4.0.3.0/release)
	Expected version: 1.13-1.13.1 PH
	Protocol version: 401
	Data version: 1519
	File location: C:\Users\<USERNAME>\Desktop\MultiMC\instances\WDL\.minecraft\bin\minecraft.jar

-- World Downloader Mod - Extensions --
Details:
	Number loaded: 2
	Hologram: Id: Hologram
Version: 2.0
Display name: Hologram support
Main author: Pokechu22
Description: 
Provides basic support for disabling holograms.
Main class: wdl.HologramHandler
Containing file: C:\Users\<USERNAME>\Desktop\MultiMC\instances\WDL\.minecraft\bin\minecraft.jar
Implemented interfaces (2)
0: wdl.api.IEntityManager
1: wdl.api.IWDLModDescripted
Superclass: java.lang.Object
Classloader: sun.misc.Launcher$AppClassLoader@5c647e05 (sun.misc.Launcher$AppClassLoader)
Annotations (0)

	EntityRealigner: Id: EntityRealigner
Version: 1.0
Display name: Entity realigner
Main author: Pokechu22
Description: 
Realigns entities to their serverside position to deal with entities that drift clientside (for example, boats).
Main class: wdl.EntityRealigner
Containing file: C:\Users\<USERNAME>\Desktop\MultiMC\instances\WDL\.minecraft\bin\minecraft.jar
Implemented interfaces (2)
0: wdl.api.IEntityEditor
1: wdl.api.IWDLModDescripted
Superclass: java.lang.Object
Classloader: sun.misc.Launcher$AppClassLoader@5c647e05 (sun.misc.Launcher$AppClassLoader)
Annotations (0)


-- World Downloader Mod - State --
Details:
	minecraft: cfi@4ce2f4d6
	worldClient: ~~NULL~~
	networkManager: ~~NULL~~
	thePlayer: ~~NULL~~
	windowContainer: ~~NULL~~
	lastClickedBlock: ~~NULL~~
	lastEntity: ~~NULL~~
	saveHandler: ~~NULL~~
	chunkLoader: ~~NULL~~
	newTileEntities: {}
	newEntities: {}
	newMapDatas: {}
	downloading: false
	isMultiworld: false
	propsFound: false
	startOnChange: false
	overrideLastModifiedCheck: false
	saving: false
	worldLoadingDeferred: false
	worldName: WorldDownloaderERROR
	baseFolderName: WorldDownloaderERROR
	baseProps: wdl.config.Configuration@58070889
	worldProps: wdl.config.Configuration@5c71329f
	globalProps: wdl.config.Configuration@225fc6a2
	defaultProps: wdl.config.DefaultConfiguration@7940d27b

-- World Downloader Mod - Base properties --
Details:
	-: empty

-- World Downloader Mod - World properties --
Details:
	-: empty

-- World Downloader Mod - Global properties --
Details:
	-: empty

-- System Details --
Details:
	Minecraft Version: 1.13
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_171, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 580492560 bytes (553 MB) / 765460480 bytes (730 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
</pre>
</details>

**Comment by Pokechu22** [comment] 2018-09-18 17:19
Thanks.  That looks like it's the same issue supremerinomemerino [was experiencing on the forums](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2520465-1-12-2-1-11-2-1-10-2-1-8-9-world-downloader-mod?comment=638); it's caused by bungeecord and should be fixed in the next version (which I'll be releasing as soon as I've fixed a few other bugs).

**Comment by Pokechu22** [comment] 2018-09-19 23:50
This should be fixed in [version 4.0.3.1](https://github.com/Pokechu22/WorldDownloader/releases/tag/v4.0.3.1).

**Closed as completed by Pokechu22** 2018-09-19 23:50 UTC
Labels: bug
