### ISSUE TITLE
WorldDownloader can be crashed with a server-side plugin and the Plugin Messaging API

### ISSUE THREAD

**Issue by bmintz** [Pokechu22/WorldDownloader#35] opened 2016-08-11 06:02 UTC
Please see [AntiWDL.java line 34](https://github.com/Redrield/AntiWDL/blob/93ab2527b9508e51f00d0f691769305b7e87c68b/src/main/java/io/github/redrield/antiwdl/AntiWDL.java#34) for more info.

Chatlog from the dev:

``` irc
<Redrield> When the client receives the WDL|CONTROL packet I send, it just dies
<bmintz> ah i see and 41 and 42 is just in case it doesn't or... does the client actually see that
<Redrield> Apparently my code trips off an EOFException
<Redrield> and the client just aborts and kills itself
<bmintz> and i'm guessing WDL uses WDL|CONTROL
<Redrield> Yeah
<bmintz> ok
<Redrield> WDL|INIT is a packet sent, saying that a client is A. Using WDL, and B. Is ready to receive permissions
<Redrield> I listen for that and send back a WDL|CONTROL packet, basically saying that they're not allowed to do anything
<Redrield> And it shows that by crashing their client
```

It's a Sponge plugin, but it should be trivial to port to Bukkit/Forge. This is essentially a more forceful WDL ServerSide Companion.

**Comment by Pokechu22** [comment] 2016-08-11 15:02
Yea, I'll fix this (probably by disabling the plugin message API if an exception occurs to discourage trying to crash it). 

The problem is, of course, the vanilla _client_ can be crashed with malformed packets, and if I recall correctly any issue about that is closed as "Works as intended".  So it's not possible to stop all misuse unfortunately.

@Redrield: If you need help with forming a valid packet, I'd be happy to help here.  I can also help in #mcdevs in a day or two, but I don't have access to an IRC client right now.

**Comment by bmintz** [comment] 2016-08-11 16:05
So will you fix it or...?

@Redrield wants no part in this I reckon, as he created that plugin for their server and got a little annoyed that I told you this.

**Comment by bmintz** [comment] 2016-08-11 16:06
Sorry I don't mean to sound pushy I just got somewhat confused by your message.

**Comment by Redrield** [comment] 2016-08-11 16:25
I didn't say that I didn't want to make a malformed packet, in fact I made that plugin with all good intentions of just disabling the functionality of WDL when a packet in the WDL|INIT channel was received.

Some more notes about why this is happening, it only occurs when I send WDL|CONTROL0, if I send any other packets to the client, no crash occurs (They're also still able to use WDL, even if I send WDL|CONTROL1, saying that they have no permissions.

**Comment by Pokechu22** [comment] 2016-08-11 16:44
Yea, I'll fix it.

@Redrield:  Probably the crash happens from different internal formatting between the way WDL expects the message and the way Sponge does.  You might have more success if you used a raw channel outbound too.

With `WDL|CONTROL` 1, is anything logged in chat if you turn on "Plugin channel message" in WDL's message options?

**Comment by Redrield** [comment] 2016-08-11 16:51
@Pokechu22 These messages pop up when I do that:
[WorldDL] Sending plugin channel registration
[WorldDL] Receiving unknown settings packet #16777216. See log for binary contents

**Comment by Redrield** [comment] 2016-08-11 16:56
One little update here, it seems that if I send WDL|CONTROL 0 through a raw data channel (Write the discriminator and boolean manually) it works, it's only the indexed channel that causes a crash

**Comment by Pokechu22** [comment] 2016-08-11 18:26
`#16777216` confirms what I thought – in hex it's 0x01000000.  Most likely the 000000 part wasn't written as part of the discriminator, but instead the payload (your disabled permissions).  

What that means is that Sponge is probably encoding the discriminator as a byte or VarInt, rather than a full into that WDL expects.  I don't know Sponge well enough to know if you can change that directly or if your only option is to use raw channels.

The reason packet 0 caused a crash probably was the length of the packet: only the discriminator and a boolean (1 byte).  If it was written with the discriminator as 1 byte as well, that's only 2 total bytes.  And the discriminator is read as a 4 byte int, so that would fail to read, causing the crash.

On the other hand, packet 1 is long enough for the discriminator to read successfully read.  And since it was read as 16777216, it  doesn't recognize the packet, and reads no further (avoiding the crash that would happen if it were actually read due to length).

**Comment by Redrield** [comment] 2016-08-11 18:45
Looking at the code for SpongeVanilla (The server I was using when I was testing this out) it looks like the message id passed gets converted to a byte, and then is mapped alongside the Class<? extends Message> that gets passed with it. https://github.com/SpongePowered/SpongeVanilla/blob/bleeding/src/main/java/org/spongepowered/server/network/VanillaIndexedMessageChannel.java#L67 is where the message gets registered, https://github.com/SpongePowered/SpongeVanilla/blob/bleeding/src/main/java/org/spongepowered/server/network/VanillaIndexedMessageChannel.java#L135 is where the packet gets created (The return value is just sent to the EntityPlayer's connection

**Closed** 2018-07-19 01:40 UTC
