### ISSUE TITLE
Tripwire strings not saved

### ISSUE THREAD

**Issue by GrapeJamMan** [Pokechu22/WorldDownloader#52] opened 2017-03-04 15:37 UTC
As title, tripwire strings are not saved. 

Using version 4.0.0.1 LiteLoader version against Minecraft 1.11.2

**Comment by Pokechu22** [comment] 2017-03-04 16:42
Hm.  Not saved, or saved, but "pop off" on load, or "not saved in the right state"?

This is odd, since while tripwire is a weird block (it has a large number of block states and only 2 "real" states), the mod's save code shouldn't have trouble with it.  I'll look into it.

**Comment by GrapeJamMan** [comment] 2017-03-04 16:57
I wish I could tell the difference, I'm pretty new at this.

When opened in single player mode, I am able to place a string between the tripwire switches, as if it never existed. Not sure if that's a helpful clarification!

**Comment by Pokechu22** [comment] 2017-03-04 16:58
Is there a string item lying on the ground nearby?  (I'm going to assume probably not, but if there is, that changes the likely cause)

**Comment by GrapeJamMan** [comment] 2017-03-04 17:01
Nope, no fallen / broken items on the floor.

**Comment by Pokechu22** [comment] 2017-03-11 19:21
I haven't been able to reproduce this, unfortunately.  Can you post a screenshot of the setup you were trying to save?

**Comment by Tsoccerguy3** [comment] 2017-03-12 08:16
I tested mod-1.11.2-baseedit-4.0.0.2-SNAPSHOT-mc1.11.2 , using complex trip wire setup . it was reproduced on the wdl map 100 % . Trip wires can be World Edited on to any block , even places they don't normally attach to ie... stairs , ice , fence etc .. and they will stay until a block update happens then they pop off . I suggest you put a sample map up . download this tripwire setup and zip it up so i can look at it in MCEdit .  Confirmed this only happens in 1.11.2 4.0.0.1 litemod version

**Comment by GrapeJamMan** [comment] 2017-03-12 12:16
I can give it a spin with the snapshot, is there a litemod package I can use to drop it in? Or maybe just wait until the release? :)

**Comment by GrapeJamMan** [comment] 2017-03-12 12:20
Not super complicated, but I pulled this morning the linked world [minecartrapidtransit_net_2017-03-12_08-01-09](https://mega.nz/#!G8RVgb7Q!cBUDX6yQ85SHSa6yin3_c0q8z5-cCY3JjrOrE5ZVhJE)

Around -29, 53, 52, inside the "station" going forward and to the right (break the gold blocks for a safe way to get in) there's a rail going up and three trip wires near a piston and diamond block that definitely exists on the multiplayer map but missing when I opened it local.

**Comment by Tsoccerguy3** [comment] 2017-03-12 19:07
on mega download , need the decryption key to get it . At this Time , no litmods working . All I know now is that the core mods work for string on trip wire switch . Suspect its a litemod transformer issue . If you want , get MCEdit here http://www.mcedit-unified.net/ . Only open the map in MCEdit , you can look at a block its state by highlighting it and holding alt key . you can then fix the map .

**Comment by Pokechu22** [comment] 2017-03-12 19:21
Hm, litemod only would be odd...  but possible.  I'll double-check.

I do remember from the time I was on minecartrapidtransit (maybe a year ago) that a few stations were previously missing some blocks - I should check the log video to double check, might have been that one (in which case... something's wonky if it works on the server).  It's entirely possible that a tripwire's somehow in an invalid state which causes the mod to freak out.

Also, to be clear, 4.0.0.2-SNAPSHOT is the version number for the current code; it hasn't been released yet (when it is released it'll be 4.0.0.2; SNAPSHOT means "as-is in development").

> on mega download , need the decryption key to get it 

The link works for me, odd.

**Comment by Pokechu22** [comment] 2017-03-12 21:47
OK, I looked through my old information.  The broken station was C9, which I'm pretty sure isn't the one you describe, and the problem was a non-slanted rail.

I found the relevant blocks in MC-edit, and they were purely air, not a tripwire with invalid data.  Interesting...

**Comment by Pokechu22** [comment] 2017-03-12 22:18
I just remembered something old.  During the 1.9 snapshots, [tripwire would randomly be deleted on load](https://bugs.mojang.com/browse/MC-94104 "[MC-94104] Floating tripwire disappears since 15w50a").  That _shouldn't_ affect the mod, given that this isn't 1.9, but it's of note.  Does MRT use a multi-protocol support plugin (such as ViaVersion)?  If so, it might be a bug in that plugin, and I'll need to ask the devs of it about it (or fix it myself).

There's also some more recent bugs, [one involving realms](https://bugs.mojang.com/browse/MC-110962 "[MC-110962] String disappearing on realms") and another [involving mobs](https://bugs.mojang.com/browse/MC-101820 "[MC-101820] Tripwire Hooks Stay in Active position with no entities to trigger them.").  Both of those seem unlikely (though the realms one is odd and something I _would_ investigate if I had realms), but are worth noting.

**Comment by Pokechu22** [comment] 2017-03-26 22:36
[Version 4.0.0.2](https://github.com/Pokechu22/WorldDownloader/releases/tag/v4.0.0.2) has been released; can you try again in that version?  If it still happens, can you post the log file (I added some additional debug code to diagnose this behavior).

**Comment by Pokechu22** [comment] 2017-07-15 01:05
I know that this is a bit late, but did you have forge installed at the time?  There is (was, at least) a forge bug (MinecraftForge/MinecraftForge#3924) that causes string to disappear; I'm investigating that but it may be that that bug is the cause.

**Comment by Pokechu22** [comment] 2017-07-19 21:45
Since the forge bug in question has been fixed (**but in 1.12 only**), I'm closing the issue.  If you're using an older MC version and forge, you can avoid that bug by ensuring you only download the world when you first login to a server after starting the game (not after reloging or entering a single player world, although changing servers via bungee is OK).

**Closed as completed by Pokechu22** 2017-07-19 21:45 UTC
Labels: bug
