### ISSUE TITLE
Support 1.16.1

### ISSUE THREAD

**Issue by F4brizio** [Pokechu22/WorldDownloader#186] opened 2020-08-09 20:12 UTC
Is a version compatible with minecraft 1.16.1 planned? When will it come out?

P.S. Thank you very much for your work.

**Comment by Pokechu22** [comment] 2020-08-09 20:27
Duplicate of #180.  I'm working on it, and I'll hopefully have something ready before 1.16.2 comes out in a few days, but I can't promise it.

**Closed as completed by Pokechu22** 2020-08-09 20:27 UTC
Labels: duplicate

**Comment by Pokechu22** [comment] 2020-08-11 07:56
https://github.com/Pokechu22/WorldDownloader/releases/tag/v4.1.0.0

**Comment by F4brizio** [comment] 2020-08-11 16:24
I love you ♥ Thank you
