### ISSUE TITLE
Bug: World Downloader 4.0.5.3 Crashes on Virtual Enderchest Close

### ISSUE THREAD

**Issue by ghost** [Pokechu22/WorldDownloader#146] opened 2019-12-18 23:09 UTC
When trying to save the contents of my virtual enderchest (the /ec command) on Skycade, the whole client (version 4.0.5.3 - MultiMC) will crash. I believe this is a result of a lack of real chest. This should instead output that the chest could not be saved.

This was tested on both pure vanilla 1.14.4 and combined with Fabric.

**Comment by Pokechu22** [comment] 2019-12-19 00:00
See https://github.com/Pokechu22/WorldDownloader/issues/137#issuecomment-520192388.  The issue isn't so much that there isn't a chest where you're looking (that is handled), but instead that there is no block in your line of site at all.  You should be able to work around that issue by looking at some block when you open the virtual enderchest (it doesn't need to be, and probably shouldn't be, a chest; if you do look at a chest it'll probably save the contents into it).

There should be a basic fix for this in the next version (I've already written one, just not pushed it due to a bunch of other less stable work going on right now).

**Comment by ghost** [comment] 2019-12-19 04:10
You are right. It throws an error message (without crashing) when I look at a block.

**Comment by Pokechu22** [comment] 2019-12-30 04:26
I've released [Version 4.0.6.0](https://github.com/Pokechu22/WorldDownloader/releases/tag/v4.0.6.0) that should fix the crash.

**Closed as completed by Pokechu22** 2019-12-30 04:26 UTC
Labels: bug
