### ISSUE TITLE
Crashes when downloading on pvp.thearchon.net

### ISSUE THREAD

**Issue by RenegadeB5** [Pokechu22/WorldDownloader#45] opened 2017-01-01 15:26 UTC
```
---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 1/1/17 10:14 AM
Description: Ticking memory connection

java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388)
	at ary.a(SourceFile:153)
	at ary.a(SourceFile:49)
	at arm.a(SourceFile:389)
	at bgw.a(SourceFile:254)
	at qs.a(SourceFile:174)
	at bfh.a(SourceFile:870)
	at qs.c(SourceFile:104)
	at qr.<init>(SourceFile:39)
	at qq.a(SourceFile:231)
	at qq.a(SourceFile:263)
	at sn.a(SourceFile:225)
	at sn.c(SourceFile:277)
	at sn.a(SourceFile:132)
	at rq.b(SourceFile:96)
	at rq.c(SourceFile:54)
	at gr.a(SourceFile:187)
	at rc.c(SourceFile:151)
	at net.minecraft.server.MinecraftServer.z(SourceFile:625)
	at net.minecraft.server.MinecraftServer.y(SourceFile:531)
	at cyk.y(SourceFile:155)
	at net.minecraft.server.MinecraftServer.run(SourceFile:447)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.Random.nextInt(Random.java:388)
	at ary.a(SourceFile:153)
	at ary.a(SourceFile:49)
	at arm.a(SourceFile:389)
	at bgw.a(SourceFile:254)
	at qs.a(SourceFile:174)
	at bfh.a(SourceFile:870)
	at qs.c(SourceFile:104)
	at qr.<init>(SourceFile:39)
	at qq.a(SourceFile:231)
	at qq.a(SourceFile:263)
	at sn.a(SourceFile:225)
	at sn.c(SourceFile:277)
	at sn.a(SourceFile:132)
	at rq.b(SourceFile:96)
	at rq.c(SourceFile:54)
	at gr.a(SourceFile:187)

-- Ticking connection --
Details:
	Connection: gr@dabdea
Stacktrace:
	at rc.c(SourceFile:151)
	at net.minecraft.server.MinecraftServer.z(SourceFile:625)
	at net.minecraft.server.MinecraftServer.y(SourceFile:531)
	at cyk.y(SourceFile:155)
	at net.minecraft.server.MinecraftServer.run(SourceFile:447)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows XP (x86) version 5.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 121030992 bytes (115 MB) / 251953152 bytes (240 MB) up to 1037959168 bytes (989 MB)
	Mod Pack: Unknown / None
	LiteLoader Mods: 1 loaded mod(s)
          - LiteModWDL version 1.8
	LaunchWrapper: 9 active transformer(s)
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: wdl.litemod.EventTransformerWDL
          - Transformer: com.mumfrey.liteloader.transformers.event.EventTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.json.ModEventInjectionTransformer
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [qw['RenegadeB5'/7, l='TheArchon - Raid2', x=2428.80, y=51.50, z=-2997.10]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'LiteLoader'
```

No idea how to fix

**Comment by RenegadeB5** [comment] 2017-01-01 15:35
```
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 1/1/17 10:26 AM
Description: Ticking memory connection

java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388)
	at ary.a(SourceFile:153)
	at ary.a(SourceFile:49)
	at arm.a(SourceFile:389)
	at bgw.a(SourceFile:254)
	at qs.a(SourceFile:174)
	at bfh.a(SourceFile:870)
	at qs.c(SourceFile:104)
	at qr.<init>(SourceFile:39)
	at qq.a(SourceFile:231)
	at qq.a(SourceFile:263)
	at sn.a(SourceFile:225)
	at sn.c(SourceFile:277)
	at sn.a(SourceFile:132)
	at rq.b(SourceFile:96)
	at rq.c(SourceFile:54)
	at gr.a(SourceFile:187)
	at rc.c(SourceFile:151)
	at net.minecraft.server.MinecraftServer.z(SourceFile:625)
	at net.minecraft.server.MinecraftServer.y(SourceFile:531)
	at cyk.y(SourceFile:155)
	at net.minecraft.server.MinecraftServer.run(SourceFile:447)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.Random.nextInt(Random.java:388)
	at ary.a(SourceFile:153)
	at ary.a(SourceFile:49)
	at arm.a(SourceFile:389)
	at bgw.a(SourceFile:254)
	at qs.a(SourceFile:174)
	at bfh.a(SourceFile:870)
	at qs.c(SourceFile:104)
	at qr.<init>(SourceFile:39)
	at qq.a(SourceFile:231)
	at qq.a(SourceFile:263)
	at sn.a(SourceFile:225)
	at sn.c(SourceFile:277)
	at sn.a(SourceFile:132)
	at rq.b(SourceFile:96)
	at rq.c(SourceFile:54)
	at gr.a(SourceFile:187)

-- Ticking connection --
Details:
	Connection: gr@16745f1
Stacktrace:
	at rc.c(SourceFile:151)
	at net.minecraft.server.MinecraftServer.z(SourceFile:625)
	at net.minecraft.server.MinecraftServer.y(SourceFile:531)
	at cyk.y(SourceFile:155)
	at net.minecraft.server.MinecraftServer.run(SourceFile:447)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows XP (x86) version 5.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 86611800 bytes (82 MB) / 254222336 bytes (242 MB) up to 1037959168 bytes (989 MB)
	Mod Pack: Unknown / None
	LiteLoader Mods: 1 loaded mod(s)
          - LiteModWDL version 1.8
	LaunchWrapper: 9 active transformer(s)
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: wdl.litemod.EventTransformerWDL
          - Transformer: com.mumfrey.liteloader.transformers.event.EventTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.json.ModEventInjectionTransformer
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [qw['RenegadeB5'/12, l='TheArchon - RAID', x=2386.20, y=51.50, z=-2988.43]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'LiteLoader'
```



crashes when ever i try to open a world from the end

**Comment by Pokechu22** [comment] 2017-01-01 18:33
That's an unusual one.  However, hopper tells me that [it's not exclusive to the mod](http://hopper.minecraft.net/crashes/minecraft/MCX-2326187/#tab_crash-info).  There's a couple of vanilla tickets - [MC-74035](https://bugs.mojang.com/browse/MC-74035) is a complete match; [MC-70008](https://bugs.mojang.com/browse/MC-70008) isn't but sounds similar.  [MC-46082](https://bugs.mojang.com/browse/MC-46082) is probably the closest match - the title helps: "Crashes when populating a chunk with empty (void) columns" - but it was supposedly fixed in a 1.8 prerelease.

I'll look into this issue more closely.  However, you _might_ be able to work around it by downloading more of the void area in the end, and then not getting close to it later.  The end doesn't have generation disabled by WDL, only the overworld, and in 1.8 the end generator can generate a _lot_ of stuff, so if there's a buffer to avoid additional generation _hopefully_ the crash should go away.

**Comment by RenegadeB5** [comment] 2017-01-01 19:36
if it helps, the server i play on is a factions server and they world edited the end so that the void is filled with end stone.

**Comment by RenegadeB5** [comment] 2017-01-01 23:17
i tried downloading more of the area, still didnt work. The worst part is that it used to work, and i dont recall changing anything. Could it have something to do with the multi world support thing?

**Comment by Pokechu22** [comment] 2017-01-01 23:19
No, multiworld support shouldn't make a difference here.  Not sure what could have changed (maybe something on the server's side).

Can you upload a zipped copy of the world onto this issue?

**Comment by RenegadeB5** [comment] 2017-01-01 23:30
https://www.mediafire.com/?gwpb1ocjrt0cvd9

idk why all the individuel files of the world go into the zip like that but you can just create a folder and then add them to it. there is a small chance this could be my computers fault because it runs windows xp lol

**Comment by Pokechu22** [comment] 2017-01-01 23:45
Yea, that's a weird zip, but I did get it to work.

And I can confirm that that world crashes, even on vanilla 1.8.  On the other hand, it seems to work fine on 1.8.9.  It also seems like it works fine if it's loaded in 1.8.9 and then reloaded in 1.8.  [Here's that for that map](https://github.com/Pokechu22/WorldDownloader/files/680245/TheArchon.-.RAID.-.loadedin1.8.9.zip).

I'm not sure if this issue is one that I can directly fix, given that it seems to be a vanilla issue.  I'll look into it, though.

**Comment by RenegadeB5** [comment] 2017-01-01 23:50
k ill try in diff versions

ill give feed back

**Comment by RenegadeB5** [comment] 2017-01-01 23:54
k it acually worked
it will be a pain to switch vesions but it isnt that bad...

**Comment by Pokechu22** [comment] 2018-03-05 03:32
Closing this issue, over 1 year old and apparently caused by 1.8.

**Closed as completed by Pokechu22** 2018-03-05 03:32 UTC
