### ISSUE TITLE
Hope you can make a Fabric version

### ISSUE THREAD

**Issue by SolidBlock-cn** [Pokechu22/WorldDownloader#200] opened 2020-12-07 12:50 UTC
Fabric is as popular as Forge, and it's the main modloader 1.16+ players use. Maybe you can update a Fabric version of the mod.
Related issue: #133

**Comment by Pokechu22** [comment] 2020-12-07 19:08
Closing as duplicate of #133.  Fabric support is still planned.

**Closed as completed by Pokechu22** 2020-12-07 19:08 UTC
Labels: duplicate, fabric
