### ISSUE TITLE
World Downloander - WTD 1.15.2?

### ISSUE THREAD

**Issue by ReneSamajStudio** [Pokechu22/WorldDownloader#154] opened 2020-02-15 08:45 UTC
Hi can you please make WTD - World Downloander 1.15.2??

im realy hoop new version is close.... every hour im restarting your github wait for new version ;[ i need this for my work

**Comment by uyjulian** [comment] 2020-02-15 08:46
duplicate of #153

**Closed as completed by uyjulian** 2020-02-15 08:46 UTC
